//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetBookModelContainer : DbContext
    {
        public PetBookModelContainer()
            : base("name=PetBookModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Veterinarian> Veterinarians { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
    }
}
